### ISSUE TITLE
option lang in google CSE fundamental

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#119]
We work on linguistic territory, the lang option is fundamentale (ex "Francois Hollande")

**Comment by DavidBruant** [comment]
> We work on linguistic territory

Yes we do. Maybe we should push the idea to its end, that is forcing the user to pick a language territoire-wide. It's unlikely a territoire with queries with different languages will make any sense especially given we'll have to do text analysis and compare them. Working with different languages within the same territoire will open the door to biaises we don't even begin to understand.

If a language is chosen at the territoire level, then oracle queries could be pre-wired to search only within the territoire language.

Let's talk about this at some point.

**Comment by DavidBruant** [comment]
Per discussion on the phone:
* Let's do this right now as it's blocking studies
* It may be interesting to study how communities in different languages are structured within the same territoire, so a territoire may have different languages.

**Comment by DavidBruant** [comment]
GCSE lang restriction happens via the `lr` parameter. See https://developers.google.com/custom-search/json-api/v1/reference/cse/list

**Comment by DavidBruant** [comment]
Done at #170
