### ISSUE TITLE
Management Oracles (Google Custom Search and Bing)

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#12]
Develop a query dispenser to the Oracles.
Each query is translated and sent for each oracle chooses the oracle.
urls (CITED) are received from the oracle and registered under the request. (the oracle is like a primary validated urls linking to the cited urls).
Make a list of available oracles (Search, social bookmarking, social media index)

**Comment by DavidBruant** [comment]
Done Architecture and GCSE in https://github.com/MyWebIntelligence/MyWebIntelligence/pull/43 (more coming like #60 and others)
