### ISSUE TITLE
Scrap/Crawl each url

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#13]
Retrieve the metadata of the page (title, description, keywords, etc.)
Recover the content of the page (title, Hn, text units containing bolds, italics, keyword query, the keywords of the page)
Detect the main container (ouch !!!)
Clean text in formating mode and save in content variable
Detect the link of the RSS feed
Measuring ContentLength variable content
Detect the presence of image, video and links cited in the main container

**Comment by DavidBruant** [comment]
A good share of it has been done at the occasion of https://github.com/MyWebIntelligence/MyWebIntelligence/pull/68
