### ISSUE TITLE
Consider removing PageRank and replace with local pagerank

### ISSUE THREAD

**Issue by DavidBruant** [MyWebIntelligence/MyWebIntelligence#156]
It looks worthless.

https://en.wikipedia.org/wiki/PageRank#Google_Toolbar
"The Google Toolbar's PageRank is updated infrequently, so the values it shows are often out of date."

**Comment by alakel** [comment]
Yes...hard to think about it...kind of nostalgia

**Comment by alakel** [comment]
Studing the meaning of local page rank and global page rank

**Comment by DavidBruant** [comment]
Compute local pagerank with https://github.com/anvaka/ngraph.pagerank

**Comment by DavidBruant** [comment]
To re-order pages, compute deciles and sort over social impact.
