### ISSUE TITLE
Add annotations (social signals and human annotations) to CSV

### ISSUE THREAD

**Issue by DavidBruant** [MyWebIntelligence/MyWebIntelligence#179]

**Comment by alakel** [comment]
The matrix
https://docs.google.com/spreadsheets/d/1y2-zKeWAD9POD_hjth-v4KlMlm5HqD7tzKvbPilLb4o/edit?usp=sharing

Export CSV : No need Content but Description (meta html OR meta Twitter OR Facebook OR GPlus OR 640 first caract of content)

**Comment by DavidBruant** [comment]
Began at https://github.com/MyWebIntelligence/MyWebIntelligence/pull/182

**Comment by alakel** [comment]
Too many social media annotation remains empty in CSV. A good option is to make an empty field and ask to test an external source such sharedcount and other free API. 
https://docs.sharedcount.com/
(Idem for google plus) . Thus no one could reach to the max of quotas. The idea is to create one or two redundant call provider in annotation ( 3 sources in all).

**Comment by alakel** [comment]
Dependancy=redundance

**Comment by alakel** [comment]
And for no Google page Rank the convention is 0 not 12.

**Comment by alakel** [comment]
Trying the free quotas of Moz... https://moz.com/products/api/pricing

**Comment by alakel** [comment]
When update the territory retrying the empty cell for social annontation

**Comment by DavidBruant** [comment]
Please create a new issue with all this information. This issue is about adjusting the CSV.

**Comment by alakel** [comment]
How to fix the accent on french lang ?

**Comment by DavidBruant** [comment]
> And for no Google page Rank the convention is 0 not 12.
And a lot of cell blank are false because there are some PR...tested with http://www.calcul-pagerank.fr/derniers-sites.php

Make another issue.
I feel this is largely pointless anyway as we cannot know whether www.calcul-pagerank.fr is a better source of PR than the current solution. The fact that there is a number in some source says nothing about its accuracy or freshness. #156 ?

> How to fix the accent on french lang ?

I don't understand the question, but it seems unrelated => new issue.
This is unlikely to be worked on in this scope anyway as it relates to encoding and the work will consist in making encoding from 3 places (the web, the database and the software where the CSV is imported) work well together. A lot of work for a small value.

**Comment by DavidBruant** [comment]
Let's consider this closed and make new issues if there are still problems in this area.
