### ISSUE TITLE
Misceleanous bugs on CSV export

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#183]
1. Make a CSV from the ";" not the "," too common in excerpt.
2. Replace all fields in the ";" by a "." to avoid breaking imports.
3. When several consecutive spaces , change all consecutive spaces by a "." ( A point and a space after)
4. Only the facebook share , missing the other social networks indicators ( like facebook , twitter Share , LinkedIn Share, etc. )

**Comment by DavidBruant** [comment]
Send me the generated CSV by email so I can have a look at it. I'm using a library so that neither 1, 2 or 3 would occur. The CSV separator should be escaped in values so imports in various softwares would work. 

Note that there is no specification for CSV and each software does a bit as it pleases them without really documenting, so whatever change I make, I have no guarantee it'll work in your software. What do you use? Have you tried Google Spreadsheet?

(4 will need to be looked at separately)

**Comment by alakel** [comment]
Do not use "," because too often in the text block and it blew software during import . In all cases , no CSV import is well coded especially when using multiple data software (modalisa, google S, gephi, etc). Excluding the ";" is hardly ever used . And when it is, we do not take risks. Replaced with a "." ( Point + Space ), which does not damage the legibility of the text and does not spit import.
1. your library can choos the separator ???
2. In the fields of large content like excerpt, content, Html content its easy to make a find/replace before export. ";" by ". "
3. Some time our readibility function put an amazing number of space (strange bit convert in space ???) so we can easy make a detection of second space and more en replace it by nothing because the content are unreadeable...
5. Dont forget the naive social impact indicator

**Comment by DavidBruant** [comment]
> Do not use "," because too often in the text block and it blew software during import .
> Excluding the ";" is hardly ever used

Hoping that people will use some characters or not is not a game we can play. This is the web, people will use all characters and we need to be prepared. 
We don't have to play this game anyway. CSV have a way to work around this by escaping the separator if found in the value. That is, `,` is replaced with `","` (same for `;` if that's the separator). So the frequency of the separators in the text we use as values should not be a concern.

In any case, I'll change the separator to `;` if that helps with import in various softwares.

> Some time our readibility function put an amazing number of space (strange bit convert in space ???) so we can easy make a detection of second space and more en replace it by nothing because the content are unreadeable...

I think readability just tries to be faithful to the HTML and preserves white spaces (so the spaces come from the HTML, not Readability per se). We never took a look at the texts, now we do :-) I'll fix it.

Send me the CSV you exported by email (or copy/paste it in a comment here) so I can study it.
