### ISSUE TITLE
Annotation on Expression domain

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#185]
The expression domain must have its own table. Particularly in order to keep its own annotations.
In this case , the variables "emmeteur" and " domaintype " applied at page-level should automatically apply to all pages of a same expression domain automaticaly.

**Comment by DavidBruant** [comment]
We need communities to be stable in the UI, so we need to store in the database which **Expression domain** belongs to a given community. As a consequence, we need expression domains to exist as tangible objects. They will have their own table. It'll probably be the first step to do domain heuristics.

**Comment by DavidBruant** [comment]
## Design constraints

* Each table entry represents an expression domain.
* Relationship between expression domain is per-territoire and never stored in the database. It's inferred from relationship between resources. Maybe others forms of relationships one day.
* In the exports and the UI, most of what will appear as expression domain characteristics will still be computed from resource annotations.

## SQL

````sql
CREATE TABLE IF NOT EXISTS expression_domains (
    id           SERIAL PRIMARY KEY,
    main_url     text NOT NULL,
    title        text,
    description  text,
    keywords     text
) INHERITS(lifecycle);

-- rename annotations to resource_annotations to make room for expression_domain_annotations one day
CREATE TABLE IF NOT EXISTS annotations (
    -- ...
    expression_domain_id    integer REFERENCES expression_domains (id) NOT NULL,
    -- ...
)
````

**Comment by DavidBruant** [comment]
Done at https://github.com/MyWebIntelligence/MyWebIntelligence/pull/197
