### ISSUE TITLE
List of Result ORDER BY

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#189]
Start with a simple ranking on Google Rank and the second criterion is "SocialImpact".
Then, in a second phase , replace the google page rank by the local page rank.

**Comment by DavidBruant** [comment]
Fixing #212 as part of this.

**Comment by DavidBruant** [comment]
Fixed in #255

**Comment by DavidBruant** [comment]
It's fixed as expected, but the result is a bit disappointing since very few pages have a Google PageRank ( #156 anyway ).
