### ISSUE TITLE
Tab in select autompletion

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#190]
Add Tab to select the tag in the autocomplete .
During autocompletion , the first word in the list is selected by default for that ";" or tab select this word.

**Comment by DavidBruant** [comment]
For now, let's just make autocomplete work (it currently requires a page refresh).
No further UX work is needed until we begin working on the "tag manager"

**Comment by DavidBruant** [comment]
Autocomplete has been worked on in recent commits (to be PR'ed soon).
Next thing to be done before closing this is use the `label` attribute of options. The label is the proper text and the value is with a `;` so it actually autocompletes.
