### ISSUE TITLE
Use ElasticSearch to find territoire expression most frequent stems

### ISSUE THREAD

**Issue by DavidBruant** [MyWebIntelligence/MyWebIntelligence#204]
I [played around with ElasticSearch](https://github.com/DavidBruant/elastic-playground) and extracting the most frequent stems of a text (words alone with custom list of stop words or 2-3-4-5-grams) turns out to be a trivial task and is now a solved problem (as anticipated ;-) ).

For reference, analysis of the [English X-men Wikipedia page](https://en.wikipedia.org/wiki/X-Men): https://gist.github.com/DavidBruant/8a5ff5a9e65f932c29b7

The remaining work to integrate this to MyWI would be: 
* Make one ES index per territoire
* Analyze the text after it's been returned by Readability
* Fill in tags automatically (we're loosing the frequency in the process, it's unfortunate)
* Integrate with tag manager (or is this for later?)

**Comment by DavidBruant** [comment]
Doing a prototype was cool, now let's get to the real stuff.

For now, let's assume the end goal is to create a new field in the Expressions table. What is needed is the following:
* Detect content language
=> html@lang + https://www.npmjs.com/package/langdetect looks super-promising

* Need a list of stopwords
* 




 (invoking @alakel for this. We need the list **at least** for French and English)

**Comment by alakel** [comment]
And make weighted ponderation on word if we find it in
- request of territory
- meta title, keywords, description
- Hn
- Bold

**Comment by DavidBruant** [comment]
First shot at #257. For now, it's english-only.
Pending proper stopword list.

> And make weighted ponderation on word if we find it in

I don't understand `request of territory`. We're analyzing what the resource is taking about. Territoire-related knowledge should be orthogonal.

For the rest, weights can be found here : 
https://github.com/MyWebIntelligence/MyWebIntelligence/pull/257/files#diff-fd37f5105e03bb71e2117221fb833e26R3
Your guess is as good as mine.

**Comment by DavidBruant** [comment]
Remaining : 
* French language
* Remove word occurrences when they're found in n-grams (generalize to all subsequences)

**Comment by oncletom** [comment]
A lot of what you have done can be performed by ElasticSearch itself:

> https://www.elastic.co/guide/en/elasticsearch/guide/current/analysis-intro.html#_built_in_analyzers

Less lines of code = less problems in the future :-)

**Comment by oncletom** [comment]
(said nothing, I missed `makeIndexConfig.js`)

**Comment by oncletom** [comment]
Re the stopwords, you might want to tap into https://github.com/NaturalNode/natural/blob/master/lib/natural/util/stopwords_fr.js and even use their tf-idf algorithm to surface most important words (against a corpus).

**Comment by DavidBruant** [comment]
> Less lines of code = less problems in the future :-)

oh trust me, I know. I've read most of ES doc, blog posts and lots of SO questions for the sole purpose of understanding what I can delegate to ES.

> Re the stopwords

See #269 (let's continue the discussion there). @alakel has specific needs which are not covered by Lucene and NaturalNode lists (which are too generic and let through too many useless words). 

> tf-idf

For now, we'll go with a static list and it should do the job just fine. We'll consider tf-idf in a future iteration.

**Comment by DavidBruant** [comment]
closed by #257
