### ISSUE TITLE
External Qualification of URL

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#21]
Extract qualification data for each urls
Audience data and global influence
- Alexa Rank
- Google Page Rank

Social data sharing (likes, share, comment)
- Facebook
- Twitter
- LinkedIn
- Google more
etc.
see: http://www.googletheplanet.com/

**Comment by DavidBruant** [comment]
Reference for what's expected in exports
https://docs.google.com/spreadsheets/d/1y2-zKeWAD9POD_hjth-v4KlMlm5HqD7tzKvbPilLb4o/edit?usp=sharing

Of course this will need some database and server work.

**Comment by DavidBruant** [comment]
## Alexa Rank

### Options

* Paid for https://aws.amazon.com/fr/alexa-top-sites/
* top-1M over last month available for free https://support.alexa.com/hc/en-us/articles/200461990-Can-I-get-a-list-of-top-sites-from-an-API-
* Hacky way http://stackoverflow.com/a/6224304
* Alternative to Alexa http://stackoverflow.com/a/1041390

### Current choice

Use the global top-1M for now. For now, let's do a one-time cli tool that downloads the zip, unzip and fill the database with dedicated tables.
When doing a domain export, ask the database and add the info to the export.

## Google Page Rank

### Options

Everyone seems to be using the same hacky technique

* http://davidwalsh.name/google-pagerank
* https://www.npmjs.com/package/google-pagerank

### Current choice

Let's just use the npm package

## Facebook

### Options

Yay! Someone already did some research work on the topic!

* https://gist.github.com/jonathanmoore/2640302 For Facebook, the endpoint seems legit.
* For likes, some options are listed here http://stackoverflow.com/questions/9728279/getting-the-facebook-like-share-count-for-a-given-url
* The FQL option is interesting https://api.facebook.com/method/fql.query?query=select%20total_count,like_count,comment_count,share_count,click_count%20from%20link_stat%20where%20url=%27http://www.twistimage.com/%27&format=json

### Current choice

Let's use the fql option for now

## Twitter

* Non-official endpoint https://cdn.api.twitter.com/1/urls/count.json?url=https://www.youtube.com/watch?v=kTHNpusq654

As if we had the choice...

## LinkedIn

* https://gist.github.com/jonathanmoore/2640302#linkedin No idea how officially supported this is.

## Google more etc. see: http://www.googletheplanet.com/

??? No clue what you meant here @alakel.

**Comment by DavidBruant** [comment]
On the database side, let's do something like this:
```sql
CREATE TABLE IF NOT EXISTS social_signals (
    id           SERIAL PRIMARY KEY,
    fetched_at    timestamp without time zone  NOT NULL, 
    type -- some ENUM "facebook_like", "facebook_share", "twitter_share", etc.
    resource_id integer REFERENCES resources (id)
);
```

Another question for @alakel : 
The spreadsheet mentions "twitter like". There aren't such things. Closest is favs and it's not clear their semantics is really a like. In any case, there is no known way to get the number of favs on tweets that mention a URL. Ignoring this part for now pending an answer.

**Comment by alakel** [comment]
ALEXA WEB INFORMATION SERVICE
To test https://aws.amazon.com/fr/awis/

**Comment by alakel** [comment]
Forget Twitter Like and googleplanet seem dead
