### ISSUE TITLE
XML Parser cannot import a GEXF generated with a node which domain_title the value created from a <title> with &#1; (in the HTML version))

### ISSUE THREAD

**Issue by DavidBruant** [MyWebIntelligence/MyWebIntelligence#216]
Found a page with `<title>&#1;</title>` (and other characters in the HTML but they're likely irrelevant). Let's try to make a reduce test case out of this.

Tentative test case for Gephi (maybe Github will mess up encoding. Important part is what is before the `a` in the attribute value):
````
<?xml version="1.0" encoding="UTF-8"?>
<gexf xmlns="http://www.gexf.net/1.2draft" version="1.2">
    <graph mode="static" defaultedgetype="directed">
        <attributes class="node">
            <attribute id="domain_title" title="domain_title" type="string"/>
        </attributes>
        <attributes class="edge">
            <attribute id="weight" title="weight" type="integer"/>
        </attributes>
        <nodes>
            <node id="n1" label="n1">
                <attvalues>
                    <attvalue for="domain_title" value="a"/>
                <attvalues>
            </node>
        </nodes>
        <edges>
        </edges>
    </graph>
</gexf>
````

**Comment by DavidBruant** [comment]
Not sure what to do here. Are their forbidden unicode chars in XML? Should they just be banned from GEXF exports? escaped (weren't they already?)? replaced?
oh XML, how much you're terrible...

**Comment by DavidBruant** [comment]
Hmm... I guess the [escaping function](https://github.com/MyWebIntelligence/MyWebIntelligence/blob/3908ea334db52b6c3775a9ef3f1ddd13bf2958d8/common/graph/DOMBuilder.js#L8-L13) could be less naive.

**Comment by DavidBruant** [comment]
In JavaScript, this problematic character is represented as `'\u0001'`

**Comment by DavidBruant** [comment]
https://en.wikipedia.org/wiki/Valid_characters_in_XML suggests that U+0001 is valid in XML 1.1, but not XML 1.0. Anyway... what parser if Gephi using anyway?

**Comment by DavidBruant** [comment]
Same problem has been noticed with a meta description containing `\u0003`

**Comment by alakel** [comment]
I just pushed a issu about cleaning the title and exerpt...Maybe it's a general problem about cleaning text from title and other text field...i'm sure a readibility lib can do that before save this field. We have to find a kind of lib wich "clean" text before save it...

**Comment by alakel** [comment]
Something like that (in this kind of scope)

"What is the purpose of Medium.js?
Medium.js allows you to take total control over contenteditable elements. **This means that you can use contenteditable without fearing your user is going to enter poor or invalid HTML. It keeps things tight, organized, and semantic.**

http://jakiestfu.github.io/Medium.js/docs/

**Comment by DavidBruant** [comment]
> I just pushed a issu about cleaning the title and exerpt...

I must have missed it?

> Maybe it's a general problem about cleaning text from title and other text field...

Yes it is. The main question is: what is the set of characters that make the XML parser used in Gephi trip?

> We have to find a kind of lib wich "clean" text before save it...

It's not hard to write it ourself. To some extent, we've [already started](https://github.com/MyWebIntelligence/MyWebIntelligence/blob/3908ea334db52b6c3775a9ef3f1ddd13bf2958d8/common/graph/DOMBuilder.js#L8-L13).
What it requires is to list **the set of characters that make the XML parser used in Gephi trip**. 
Even if we're using a library, we will need to review what set of characters are cleaned.

In any case, as a matter of principle, we will never clean text **before** saving it, only after at export time. That way, if there are bugs in our code, they don't affect what is stored, only what's exported.

> .http://jakiestfu.github.io/Medium.js/docs/

This is unrelated. It seems specifically targeted at making contenteditable work (which is its own problem).

**Comment by alakel** [comment]
So we decide to not fix this bug because is a Gephi limit. So we use an XML reader like Xmplify for MAC to fix the bug : we erase the field title or description in the bug line. (3secondes fix)

**Comment by DavidBruant** [comment]
> So we decide to not fix this bug because is a Gephi limit.

Sounds good. If it ever becomes too recurring a problem, let's revisit this issue.
If you come across it again, tell me about it so I can list the guilty chars.

I don't understand the milestone. Re-assigning it.

**Comment by DavidBruant** [comment]
Another instance of `\u0003` was found in the wild

**Comment by DavidBruant** [comment]
`"\u0001\u0003\u0008".replace(/[\u0001-\u0008]/g, 'a')`

**Comment by DavidBruant** [comment]
http://www.cuisinesmultiplex.com/ has a guilty character in its meta description

**Comment by DavidBruant** [comment]
closed via https://github.com/DavidBruant/MyWebIntelligence/commit/5188d8589bc5b7b1630944f864e25015b89103d1
