### ISSUE TITLE
Turn indicators into indices by intensity and build ranking

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#225]
Indice = INTEGER_ARR_SUP([(real-min)/(max-min)]*100)
For 2 new variables
- social_impact (pages and domain)
- estimated_audience_rank (domain)

**Comment by DavidBruant** [comment]
Why the `+1`? It'll make things go from 1 to 101.
Otherwise, ok. 
To be done at the occasion of #196.

**Comment by DavidBruant** [comment]
No `+1`.
The purpose is to give measures relative to the territoire.

**Comment by DavidBruant** [comment]
Both in the UI and exports, I will keep the raw estimated audience, but add the two ranks. The social impact will only be provided as rank since it's a synthetic metrics which absolute value doesn't carry any meaning (unlike the estimated audience which is a number of individuals)

**Comment by DavidBruant** [comment]
It doesn't change anything, but min(social_impact) = 0 systematically since some pages are just never shared on social networks.

**Comment by DavidBruant** [comment]
Same goes for estimated audience (min = 100 because it's our default. When we'll have twitter/Facebook fan count, it'll be as close as 0 than can be).

**Comment by DavidBruant** [comment]
Done in #301
