### ISSUE TITLE
Button deletes no longer works on lists

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#227]
We put on ze button and that not delete

**Comment by DavidBruant** [comment]
I need steps to reproduce.

**Comment by DavidBruant** [comment]
You're possibily experiencing https://github.com/MyWebIntelligence/MyWebIntelligence/issues/195 but I don't have enough information to tell.

**Comment by alakel** [comment]
It's easy in the page list. The button Delete desapear and dont work when we click on it. Nothing happen
![capture d ecran 2015-10-15 a 15 16 15](https://cloud.githubusercontent.com/assets/6803778/10514709/b00965e6-734f-11e5-9834-8335e98138b9.png)

**Comment by DavidBruant** [comment]
Something on the console says `newAnnotation is undefined`. Not sure where the problem lies yet.

**Comment by DavidBruant** [comment]
Fixed by #243.
