### ISSUE TITLE
Export/Import territories

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#229]
When i bulid a territories with somes queries (with all parameters) i would like to save this parameters for One/ All project territories in a XML field. 

So next time (in another server or after crashed mine), i just import a project and run it...even if its a complex one.

**Comment by DavidBruant** [comment]
Make a button to export a territoire in the territoire list next to each territoire.
Make an import button as an alternative choice in the "new territoire" form.

The territoire export is a json file of the following shape:
````json
{
    name: string,
    description: string,
    queries: [
        {
            "name": string,
            "oracleNodeModuleName": string,
            "oracleOptions": string,
            "q": string
        }
    ],
    resources: [
        {
            url: string,
            annotations: {...}
        }
    ],
    expressionDomains: [
        {
            name: string,
            annotations: {...}
        }
    ]
}
````

**Comment by DavidBruant** [comment]
Done at #298
