### ISSUE TITLE
Display social annotations in the page list

### ISSUE THREAD

**Issue by DavidBruant** [MyWebIntelligence/MyWebIntelligence#254]
This will help having an intuition of how much is done and how much should be redone.
It also helps giving an indication of whether something went really wrong in the backend.

**Comment by DavidBruant** [comment]
And keep annotations always displayed

**Comment by DavidBruant** [comment]
Move `media_type` there and add `tags` (but at the expression domain this time)

**Comment by DavidBruant** [comment]
Add these variables to page CSV

**Comment by alakel** [comment]
![photo](https://cloud.githubusercontent.com/assets/6803778/10997626/d681e5d6-848e-11e5-9991-0b0c041d60bb.jpg)

**Comment by DavidBruant** [comment]
Fixed by #277
