### ISSUE TITLE
Get rid of (currently) useless sigma viz and replace with domain annotation interface

### ISSUE THREAD

**Issue by DavidBruant** [MyWebIntelligence/MyWebIntelligence#267]

**Comment by DavidBruant** [comment]
Move `media_type` there and add `tags` (but at the expression domain this time)

**Comment by alakel** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/6803778/11045809/060e3bea-872a-11e5-9004-14e8c1f6357e.jpg)

**Comment by DavidBruant** [comment]
There is no `tags`. There is only an `emitter_type` and `keywords` are read-only.

**Comment by DavidBruant** [comment]
Fixed at #279
