### ISSUE TITLE
Add custom list of stopwords in French and English

### ISSUE THREAD

**Issue by DavidBruant** [MyWebIntelligence/MyWebIntelligence#269]
If all word of a stem is a stopword, erase the stem

**Comment by alakel** [comment]
A good explanation of what is a stop word

https://en.wikipedia.org/wiki/Stop_words

and

http://www.text-analytics101.com/2014/10/all-about-stop-words-for-text-mining.html

**Comment by alakel** [comment]
You will find the most common stop word list there
https://docs.google.com/spreadsheets/d/1zphu5bQomSCYNBt09xgIvY-s7peTZkLAMlwEdzZaRzc/edit?usp=sharing

**Comment by DavidBruant** [comment]
Fixed by 276.
