### ISSUE TITLE
Add  publication date for each expression

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#273]

**Comment by DavidBruant** [comment]
Where can this information be found, though? ;-)

**Comment by DavidBruant** [comment]
Trying to summarize tomorrow discussions:
* Create a new expression field which is the publication date filled with the article published date. There are currently 2 known main ways to express a publication date
    * [meta article:published_time](http://ogp.me/#no_vertical) (from Facebook open graph?)
    * [<any-element itemprop="datePublished" content="...">](https://developers.google.com/structured-data/rich-snippets/articles) (from Google for rich snippets)
* Create a new resource annotation which is a publication date
* Fill in this annotation by default with the expression value if there is such value.
* Provide some way to assist the user in finding the date (TBD at this point)

Note: the mutualisation mechanism from #286 may help having more dates filled in.

**Comment by DavidBruant** [comment]
Per discussion, in domain exports,
* The domain node `start` date is the minimum publication date of all territoire pages in the domain. 
* There is no `end` date (should probably be when all the pages disappeared from the web, but we don't have access to such information nor can we even think of how to get it)
* For a domain edge (d1 -> d2), there are a set of corresponding page edges (p1 -> p2) where p1 € d1 and p2 € d2. The domain edge `start` date is min(publicationDate(p1)) (where p1 is the source node. This asymetry is on purpose)

**Comment by DavidBruant** [comment]
Fixed at #315
