### ISSUE TITLE
When you kill a request not finished Kill all tasks not finished

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#283]

**Comment by DavidBruant** [comment]
The best way to do this is to do #126 first and then `ON DELETE CASCADE` on tasks for the `territoire_id` field

**Comment by DavidBruant** [comment]
Done alongside #126.
See https://github.com/MyWebIntelligence/MyWebIntelligence/blob/98a9734a37f94be7115de00000125d2a1e1638d3/database/management/createTables.sql#L251

In flight tasks fail as expected and don't see to bother the overall system.
