### ISSUE TITLE
Prefilling domain expression

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#286]
Collective Intelligence - Pre- filling the " type of media &type-emmeter " field with 
the mode of each variable in each expression domain if it already exists in the central memory (independently of the territories ) .
The domain form with two fields is too long. We can take productivity gain process that economists call experience performance.

**Comment by alakel** [comment]
In the pre-filling of the field, we could not look only on the first letter

**Comment by alakel** [comment]
In the precharging of the field , could all values ​​of all annotation base especially if it is pre-filled by the user .

**Comment by DavidBruant** [comment]
Let's do it this way:
Hook into `prepareExpressionDomainForTerritoire`. In parallel of an expression domain audience being estimated, fetch all ExpressionDomainAnnotations for this particular expression domain, compute the mode of the two variables if there are values at all and add that to the updated annotations for this resource.

Need to add SQL indices for lookup perf.
