### ISSUE TITLE
Lag on scrolling 2000 results and more

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#289]

**Comment by DavidBruant** [comment]
I've been working on this yesterday and this morning. I know I have made improvements, but it's hard to know whether where things are at now will be acceptable. 
I picked some of the low-hanging fruits. Perf can be improved again, but that would require significantly more work.

Let's keep the issue open, deploy on 4444 one day and decide then.

**Comment by DavidBruant** [comment]
Work has began here in #301.

Let's keep the issue open, deploy on 4444 one day and decide then.
