### ISSUE TITLE
Reference to design decisions in the repo

### ISSUE THREAD

**Issue by DavidBruant** [MyWebIntelligence/MyWebIntelligence#30]
Should design discussions/decisions be in Trello and we add links from the Github repo to there or should design happen in the Github repo?

**Comment by alakel** [comment]
For me, Trello is just a digtial dashboard for pos-it. I opt for a centralized use github throughout the production process in all aspects. Even the managment of the project in production mode. It is necessary to blow the walls between the jobs? So do across platforms ;-)

**Comment by alakel** [comment]
But maybe we have to link to Balsamiq server for get in the comments
