### ISSUE TITLE
Create a Google Account for MyWebIntelligence

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#34]

**Comment by DavidBruant** [comment]
Pending on solving the "we need your phone number" issue.

**Comment by alakel** [comment]
HAve to fixe what data we take and store ?

**Comment by DavidBruant** [comment]
This is unrelated to this issue. The Google Account is to create credentials to login with google and GCSE (today, I'm using my own account on my machine which cannot work when deployed on a server)

**Comment by DavidBruant** [comment]
This is not "Creation de Projet" in the sense of the application, this is more a "deployment" issue

**Comment by DavidBruant** [comment]
Done.

**Comment by DavidBruant** [comment]
A `Deployed MyWebIntelligence ` project has been created in `https://console.developers.google.com/project`
2 APIs have been activated:
* `Custom Search API` (for the GCSE oracle)
* `Google+ API` (for login with Google)

A CSE has been created https://cse.google.com/all with the name "MyWI générique". It crawls the web, all languages included, no specific domain provided.
