### ISSUE TITLE
Random thoughts

### ISSUE THREAD

**Issue by DavidBruant** [MyWebIntelligence/MyWebIntelligence#42]
Putting them here to not loose them. Not really an issue, but items to discuss.

* A query shouldn't be mutable since the corresponding results may not be related to the new lang/"q", etc.
* An oracle will return different results at different points in time. We may need to force the users to create the queries in one batch (or not too far away from one another) or restart the oracles.
* Maybe need to take snapshots of oracle results.

**Comment by alakel** [comment]
We need to have a documentation file with all this definition and reflexion...

**Comment by DavidBruant** [comment]
Agreed. What is the proper medium for this content?

**Comment by DavidBruant** [comment]
If these things are an issue, we'll naturally come back at them.
