### ISSUE TITLE
Créer une charte graphique de l'application

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#51]
Les inspirations sont (blanc, épuré et efficace)
BUFFER (surtout !!! )
Twitter

**Comment by DavidBruant** [comment]
Unassigning myself for obvious reasons ;-)

**Comment by alakel** [comment]
We had this discussion IRL? We talked about our incompetence in the matter and the necessity to find a graphic designer ...

**Comment by DavidBruant** [comment]
Yes we did, which is why I'm unassigning myself.

**Comment by DavidBruant** [comment]
This happened. Now time to merge the designers' work with ours.

The mockup has been added to the repo as is for now.
Plan of attack: 
- [ ] Add the necessary directories under `client`
- [ ] Change `index.html` accordingly
- [ ] Integrate changes on a page-per-page basis
    - [ ] Login
    - [ ] Territoire List
    - [ ] Territoire pages
    - [ ] Territoire domain
- [ ] Remove current CSS

**Comment by DavidBruant** [comment]
Fixed by #346
