### ISSUE TITLE
Find all Twitter accounts related to a certain search criteria

### ISSUE THREAD

**Issue by DavidBruant** [MyWebIntelligence/MyWebIntelligence#63]
> I'm looking for all the twitter accounts that talk about MDN on a regular basis. If you know some, please, let me know.

https://twitter.com/JeremiePat/status/570198724237881344

**Comment by DavidBruant** [comment]
This is just to keep this in mind for one day, not for now.

**Comment by alakel** [comment]
This issue have hiplace in TA project, keep in mind our road map on this project. Social network are not for the next release even if xe do all to prepare this issue
