### ISSUE TITLE
In crawling, the decision to approve a page depends on the expression domain

### ISSUE THREAD

**Issue by DavidBruant** [MyWebIntelligence/MyWebIntelligence#64]

**Comment by alakel** [comment]
Forget about this issue ?

**Comment by DavidBruant** [comment]
It came from the following reasoning (after we discussed):
10 approved pages each link to 1 different page but all the linked pages are within the same expression domain. We concluded that it was worth keeping all these pages. The only way to know they have something in common is to add the expression domain as part of the approval decision making process.

**Comment by alakel** [comment]
Got it

**Comment by DavidBruant** [comment]
Irrelevant now. See https://github.com/MyWebIntelligence/MyWebIntelligence/wiki/The-approval-battle
