### ISSUE TITLE
First shot of listing

### ISSUE THREAD

**Issue by DavidBruant** [MyWebIntelligence/MyWebIntelligence#74]
First shot of #15.
Need to think hard about data model, storage, API, UX to save the human time at all costs.

**Comment by DavidBruant** [comment]
At this occasion, humans will qualify over 3 variables:
* favorite (boolean)
* reject (boolean)
* type (enum)

**Comment by DavidBruant** [comment]
types (verbatim from @alakel )
Institutionnel, Thematique, Annuaire, Presse, Blog, Forum, Reseau social, Moteur de recherche

**Comment by DavidBruant** [comment]
* Create 2 tabs: one for url list, the other for domain list. See buffer interface
* move download buttons to the right
* no human qualification for April 13th (create new issue)

**Comment by alakel** [comment]
There two distinctive tasks between UX and Back

**Comment by DavidBruant** [comment]
Closed via #92
