### ISSUE TITLE
Gestion des Oracles Bis (DIIGO, Google Alert (fluxRSS))

### ISSUE THREAD

**Issue by alakel** [MyWebIntelligence/MyWebIntelligence#90]
Les différents type d'oracles (pour mémo&liste à faire)
- Moteur de recherche(Google, Yahoo, Bing, exalead, etc)
- Moteur Social Media (Buzzsumo, social searcher, etc)
- Social Bookmark (Diigo, Dig, Stumble Upon)
- Outil de curation (ScoopIt, Pearltree, Evernote, etc)

**Comment by DavidBruant** [comment]
Too vague
