### ISSUE TITLE
Human annotations - Part 1 : rejection

### ISSUE THREAD

**Issue by DavidBruant** [MyWebIntelligence/MyWebIntelligence#91]
Follow up to #74 (where qualification were dismissed)
Need to do qualification.

**Comment by alakel** [comment]
types (verbatim from @alakel )
Institutionnel, Thematique, Annuaire, Editorial, Blog, Forum, Reseau social, Moteur de recherche

**Comment by alakel** [comment]
For the type of media , the tag must be possible at the page level or at the domain level . But in any case, the tag calls the domain of expression.

**Comment by alakel** [comment]
For the label, the tag must also be able to be at the page level or at the domain level . BUT IS a label describes the domain of expression IS page .

**Comment by DavidBruant** [comment]
Per discussion yesterday, when annotating a resource, the human being can:
* choose to refuse the page
* pick a page type (list above)
* list keywords ("tags")

It's currently out of scope for a user to create their own annotations. These are the 3 hardcoded annotations (maybe keywords are each their own annotation type? tbd).


> For the type of media , the tag must be possible at the page level or at the domain level . But in any case, the tag calls the domain of expression.

Is this in scope for this issue? I assume it isn't. In any case, the expression domain is likely to become an annotation itself (see #160 ).
I don't understand what you mean by `the tag calls the domain of expression`

> For the label, the tag must also be able to be at the page level or at the domain level . BUT IS a label describes the domain of expression IS page .

I don't understand this.

**Comment by DavidBruant** [comment]
## Design

### Constraints

* Building the graph is affected by this and must take the Y/N into account. Refused pages must NOT be in the graph (nor pages found from these via linking). Ideally crawling should be affected in real time, but it sounds hard to do.
* Annotations are necessary in bulk in exports
* Annotations are necessary per page when annotating to pre-fill the annotations in the UI

### Data model

`annotation_type`
* id
* territoire_id
* resource_id
* name
* type

`type` is an enum `['boolean', 'number', 'string', 'list<string>']`. Each type as an encode/decode function pair on the Node.js side to encode/decode data to binary


`annotation_value`
* annotation_id
* user_id
* value (binary) -- this prevents annotation-based queries at the SQL level. Stats will have to be made in JS or maybe in a synthesized document served by ElasticSearch

**Comment by DavidBruant** [comment]
Annotations are about to be a long and important chapter in this project. But we need to move, so le's make a design that is purposefully reduced in scope and ambition. It is the wrong design for the future, but will get us moving more quickly. Here are some simplifying decisions:
* there can only be one annotation per (territoire, resource) pair. The user is the last user to have made a change (full modification history is lost)
* Make `annotation_values` values a 2-field thing: `accepted` (boolean default true) and `values` which will contain a JSON blob.

**Comment by DavidBruant** [comment]
Given the constraints and simplifications, here is the current design:

```sql
CREATE TABLE IF NOT EXISTS annotations (
    accepted  boolean DEFAULT true,
    values      string, -- JSON blob. This prevents annotation-based queries at the SQL level. Stats will have to be made in JS or maybe in a synthesized document served by ElasticSearch
    resource_id  integer REFERENCES resources (id) NOT NULL,
    territoire_id  integer NOT NULL, -- eventually should be a foreign key for the territoires table
    user_id  integer NOT NULL, -- eventually should be a foreign key for the users table
    PRIMARY KEY(territoire_id, resource_id) -- for now
) INHERITS(lifecycle);
CREATE TRIGGER updated_at_annotations BEFORE UPDATE ON annotations FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE INDEX ON annotations (territoire_id);
CREATE INDEX ON annotations (resource_id);
```

**Comment by DavidBruant** [comment]
Database part is done (and exports work with the new data model).
Remaining:
* UI to accept/annotate a resource (this hasn't really been designed, let's do something, show it, gather feedback and adjust).
    * delete button
    * type dropdown
    * input for tags with autocomplete
    * Use annotations to autocomplete the inputs (and type for resources from same expression domain)
* Build the graph taking `accepted` into account
* Add human annotations to CSV and GEXF exports

**Comment by alakel** [comment]
Ouch !

**Comment by DavidBruant** [comment]
> Ouch !

? Regarding a specific part?

**Comment by alakel** [comment]
Nein. just amazed by the moment

**Comment by DavidBruant** [comment]
> Nein. just amazed by the moment

It's happening bro :-p

**Comment by DavidBruant** [comment]
Regarding building the graph:
* Whenever a resource is found in the context of a territoire, an annotation needs to be created. By default, `approved: NULL`.
* The territoire and notion of approval is supposed to be atemporal. Consequently, the subgraph reached by a resource which is later dis-approved by a human being should be removed. The graph is then always re-built from the roots (because book-keeping would be tedious and mostly worthless).

**Comment by DavidBruant** [comment]
Repurpose the issue to split it in parts.
First part done in #176
